-- src/luna/memoria-embeddings-schema.sql
--
-- Reference schema for adding semantic (embedding) search to `memoria_luna`.
-- Like `hippocampus/schema.sql`, this file documents the schema this
-- runtime expects; it is not run automatically — this repository manages
-- its Supabase schema outside of migrations. Apply by hand against the
-- target Supabase project before anything that depends on the `embedding`
-- column or `buscar_memoria_semantica` goes live.

-- 1) Enables the pgvector extension (vector storage/indexing). Does not
-- generate embeddings by itself — only stores and searches vectors already
-- generated by `src/luna/embeddings.ts`.
CREATE EXTENSION IF NOT EXISTS vector;

-- 2) Embedding column on memoria_luna. 384 dimensions = output size of the
-- chosen model (Xenova/paraphrase-multilingual-MiniLM-L12-v2, see
-- src/luna/embeddings.ts). Nullable: existing rows stay unembedded until
-- processed by the backfill script
-- (src/luna/scripts/backfill-embeddings.ts).
ALTER TABLE memoria_luna ADD COLUMN IF NOT EXISTS embedding vector(384);

COMMENT ON COLUMN memoria_luna.embedding IS
  'Semantic embedding (384 dim), generated by a local open source model '
  '(Xenova/paraphrase-multilingual-MiniLM-L12-v2, via @huggingface/transformers, '
  'no API cost). NULL = not yet processed.';

-- 3) HNSW index for cosine-similarity search — the currently recommended
-- pgvector index type for most cases. Cosine is the right metric because
-- the embedding is emitted normalized (normalize: true in gerarEmbedding()).
CREATE INDEX IF NOT EXISTS idx_memoria_luna_embedding_hnsw
  ON memoria_luna
  USING hnsw (embedding vector_cosine_ops);

-- 4) Semantic search function: given a query vector, returns the N most
-- similar memories (by cosine distance), with a configurable minimum
-- similarity threshold.
CREATE OR REPLACE FUNCTION buscar_memoria_semantica(
  vetor_consulta vector(384),
  limite_resultados int DEFAULT 5,
  similaridade_minima float DEFAULT 0.5
)
RETURNS TABLE (
  id uuid,
  tipo text,
  titulo text,
  contexto text,
  similaridade float
)
LANGUAGE sql STABLE
AS $$
  SELECT
    memoria_luna.id,
    memoria_luna.tipo,
    memoria_luna.titulo,
    memoria_luna.contexto,
    1 - (memoria_luna.embedding <=> vetor_consulta) AS similaridade
  FROM memoria_luna
  WHERE memoria_luna.embedding IS NOT NULL
    AND 1 - (memoria_luna.embedding <=> vetor_consulta) >= similaridade_minima
  ORDER BY memoria_luna.embedding <=> vetor_consulta
  LIMIT limite_resultados;
$$;

-- Verification status: not executed or verified against a live Supabase
-- project by this session. The Architect reported having applied this by
-- hand against production on 2026-07-25 and observing plausible
-- similarity scores on synthetic vectors (near 1.0 for an identical
-- vector, high for a deliberately similar one, low for a deliberately
-- different one) — reported here, not independently confirmed. Re-verify
-- against the actual project state before relying on it.
